---
version: '2'
services:
  app:
    image: nicbet/phoenix:1.4.8
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app
    depends_on:
      - db
  db:
    image: postgres:10
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:

